export const APIROUTES = {
  API: {
    ENDPOINT: process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000",
    SIGNIN: "/auth/signin",
    SIGNUP: "/auth/signup",
    SIGNOUT: "/auth/signout",
    GET_USER: "/auth/user",
    GET_MOVIES: "/movies",
    GET_MOVIE: "/movies/movie",
    POST_FAVORITE_MOVIE: "/movies/favorite",
    POST_COMMENTS: "/comments",
    POST_CREATE_COMMENT: "/comments/create",
    GET_GALLERY_MOVIES: "/gallery",
    UPLOAD_POSTER: "/gallery/upload-poster",
    ADD_GALLERY_MOVIE: "/gallery",
    GET_RATING: "/movies/rating",
    POST_RATING: "/movies/rating",
    GET_FAVORITE_MOVIES: "/movies/favorite",
  },
  URL: {
    HOME: "/",
    SIGNIN: "/signin",
    SIGNUP: "/signup",
    LOGOUT: "/logout",
    MOVIES: "/movies",
    MOVIE: "/movies/[id]",
    GALLERY: "/gallery",
    FAVORITE: "/favorite",
  },
  QUERY_KEYS: {
    USER: "USER",
    MOVIES: "MOVIES",
    COMMENTS: "COMMENTS",
    CREATE_COMMENT: "CREATE_COMMENT",
    GALLERY_MOVIES: "GALLERY_MOVIES",
    RATING: "RATING",
    FAVORITE_MOVIES: "FAVORITE_MOVIES",
  },
};
