name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Step 1: Set up Node.js for both backend and frontend
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

  # Step 2: Install dependencies for the backend
  backend-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test
      - name: Build backend
        run: |
          cd backend
          npm run build

  # Step 3: Install dependencies for the frontend
  frontend-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend tests
        # run: |
        #   cd frontend
        #   npm test
      - name: Build frontend
        run: |
          cd frontend
          npm run build

  # Step 4: Deployment (Optional, based on your setup)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [backend-build, frontend-build]
  #   steps:
  #     - name: Deploy Backend
  #       run: |
  #         # Add your backend deployment commands here
  #         echo "Deploying Backend..."
  #     - name: Deploy Frontend
  #       run: |
  #         # Add your frontend deployment commands here
  #         echo "Deploying Frontend..."
