import { Movie } from "packages/types/movie.type";

export const movies: Movie[] = [
  {
    title: "Mad Max: Fury Road",
    release_date: 1430438400000,
    genre: "Action",
    poster: "/movie-poster/mad-max-fury-road.jpg",
    duration: 120,
    plot: "In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a warlord and his army.",
    comments: ["64e407f9c6f946a2a7b2e512", "64e4081ea751d29387c1d624"],
  },
  {
    title: "John Wick",
    release_date: 1414108800000,
    genre: "Action",
    poster: "/movie-poster/john-wick.jpg",
    duration: 101,
    plot: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",
    comments: ["64e4084d8c5b725b5a91ea29", "64e4085ab943c925b7e1f728"],
  },
  {
    title: "The Dark Knight",
    release_date: 1216339200000,
    genre: "Action",
    poster: "/movie-poster/the-dark-knight.jpg",
    duration: 152,
    plot: "Batman battles the Joker, a criminal mastermind who brings Gotham to its knees.",
    comments: ["64e40882dc59e28c73f2ba3c"],
  },
  {
    title: "Gladiator",
    release_date: 957139200000,
    genre: "Action",
    poster: "/movie-poster/gladiator.jpg",
    duration: 155,
    plot: "A betrayed Roman general seeks revenge on the corrupt emperor who murdered his family.",
    comments: ["64e408ae632f29d7c65b4b09", "64e408c1ad93e12f82b2d8e5"],
  },
  {
    title: "The Hangover",
    release_date: 1243891200000,
    genre: "Comedy",
    poster: "/movie-poster/the-hangover.jpg",
    duration: 100,
    plot: "Three friends wake up from a bachelor party with no memory of the night before and must find their missing friend.",
    comments: ["64e408edb6dce83a67b21c36"],
  },
  {
    title: "Superbad",
    release_date: 1187395200000,
    genre: "Comedy",
    poster: "/movie-poster/superbad.jpg",
    duration: 113,
    plot: "Two high school friends plan to party hard before graduation but face a series of mishaps.",
    comments: ["64e4091253b8e27a93d2f27e", "64e409207b36e65d98a7c3a5"],
  },
  {
    title: "Groundhog Day",
    release_date: 728524800000,
    genre: "Comedy",
    poster: "/movie-poster/groundhog-day.jpg",
    duration: 101,
    plot: "A weatherman finds himself living the same day over and over again.",
    comments: ["64e4094b6e5c29b95e9b61d1"],
  },
  {
    title: "Step Brothers",
    release_date: 1216684800000,
    genre: "Comedy",
    poster: "/movie-poster/step-brothers.jpg",
    duration: 98,
    plot: "Two middle-aged men become stepbrothers and must learn to coexist.",
    comments: ["64e4096e75cbf93c58a7d39b"],
  },
  {
    title: "The Shawshank Redemption",
    release_date: 780969600000,
    genre: "Drama",
    poster: "/movie-poster/the-shawshank-redemption.jpg",
    duration: 142,
    plot: "Two imprisoned men bond over a number of years, finding solace and redemption through acts of decency.",
    comments: ["64e4098c75f6f93d93b1d7e3"],
  },
  {
    title: "Forrest Gump",
    release_date: 774144000000,
    genre: "Drama",
    poster: "/movie-poster/forrest-gump.jpg",
    duration: 142,
    plot: "The story of a man with low intelligence who witnesses and influences historical events.",
    comments: ["64e409adad9bc29e82d3e1c6"],
  },
  {
    title: "Fight Club",
    release_date: 939772800000,
    genre: "Drama",
    poster: "/movie-poster/fight-club.jpg",
    duration: 139,
    plot: "An insomniac office worker forms an underground fight club with a soap salesman.",
    comments: ["64e409ce7b7f2e4b85b7f6c3", "64e409d8a5cbd39c97a8f3b6"],
  },
  {
    title: "The Godfather",
    release_date: 68762880000,
    genre: "Drama",
    poster: "/movie-poster/the-godfather.jpg",
    duration: 175,
    plot: "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.",
    comments: ["64e409f4765cb1b93d1d8b79"],
  },
  {
    title: "The Conjuring",
    release_date: 1374105600000,
    genre: "Horror",
    poster: "/movie-poster/the-conjuring.jpg",
    duration: 112,
    plot: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    comments: ["64e40a0ec5b7f1b2d4c9a672"],
  },
  {
    title: "A Nightmare on Elm Street",
    release_date: 466214400000,
    genre: "Horror",
    poster: "/movie-poster/a-nightmare-on-elm-street.jpg",
    duration: 91,
    plot: "Teenagers are terrorized in their dreams by Freddy Krueger, a killer who can strike them in their sleep.",
    comments: ["64e40a18364e2f2d7c8e3f2b"],
  },
  {
    title: "Hereditary",
    release_date: 1528329600000,
    genre: "Horror",
    poster: "/movie-poster/hereditary.jpg",
    duration: 127,
    plot: "A family is haunted by disturbing occurrences and dark secrets following the death of their matriarch.",
    comments: ["64e40a254c7b7d8c91b1e5b3"],
  },
  {
    title: "The Shining",
    release_date: 327456000000,
    genre: "Horror",
    poster: "/movie-poster/the-shining.jpg",
    duration: 146,
    plot: "A man takes a job as a winter caretaker at an isolated hotel, where he succumbs to madness and violence.",
    comments: ["64e40a336c8f9b8a9a7d9f51"],
  },
  {
    title: "Inception",
    release_date: 1278633600000,
    genre: "Science-Fiction",
    poster: "/movie-poster/inception.jpg",
    duration: 148,
    plot: "A thief who enters the dreams of others is tasked with planting an idea deep within the mind of a powerful figure.",
    comments: ["64e40a414b3f48b25c9d8c45"],
  },
  {
    title: "The Matrix",
    release_date: 922147200000,
    genre: "Science-Fiction",
    poster: "/movie-poster/the-matrix.jpg",
    duration: 136,
    plot: "A hacker discovers the reality he knows is an illusion and joins a rebellion against the system's controllers.",
    comments: ["64e40a4fd7e5c29c82b1d7b2"],
  },
  {
    title: "Blade Runner 2049",
    release_date: 1507248000000,
    genre: "Science-Fiction",
    poster: "/movie-poster/blade-runner-2049.jpg",
    duration: 164,
    plot: "A young blade runner discovers a long-buried secret that could plunge what's left of society into chaos.",
    comments: ["64e40a5dc64c2b5c91a7f6c4"],
  },
  {
    title: "Interstellar",
    release_date: 1415318400000,
    genre: "Science-Fiction",
    poster: "/movie-poster/interstellar.jpg",
    duration: 169,
    plot: "A group of explorers uses a newly discovered wormhole to attempt interstellar travel and ensure humanity's survival.",
    comments: ["64e40a6b7f6a3d7b95e1c3b6"],
  },
  {
    title: "The Notebook",
    release_date: 1087862400000,
    genre: "Romance",
    poster: "/movie-poster/the-notebook.jpg",
    duration: 123,
    plot: "A young couple falls in love in the 1940s, but are soon separated by war and social class differences.",
    comments: ["64e40a7898e4f1d8c72b8f16"],
  },
  {
    title: "Pride & Prejudice",
    release_date: 1136073600000,
    genre: "Romance",
    poster: "/movie-poster/pride-and-prejudice.jpg",
    duration: 129,
    plot: "Sparks fly when spirited Elizabeth Bennet meets wealthy, proud Mr. Darcy in this adaptation of Jane Austen's novel.",
    comments: ["64e40a89b9d6f3a7b85c1e72"],
  },
  {
    title: "La La Land",
    release_date: 1481068800000,
    genre: "Romance",
    poster: "/movie-poster/la-la-land.jpg",
    duration: 128,
    plot: "An aspiring actress and a jazz musician fall in love but struggle to balance their relationship with their dreams.",
    comments: ["64e40a91d76c9b8f7d2f9d6b"],
  },
  {
    title: "Titanic",
    release_date: 882489600000,
    genre: "Romance",
    poster: "/movie-poster/titanic.jpg",
    duration: 195,
    plot: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated Titanic.",
    comments: ["64e40a9f89e1d2f25b6c5f81"],
  },
  {
    title: "Toy Story",
    release_date: 816854400000,
    genre: "Animation",
    poster: "/movie-poster/toy-story.jpg",
    duration: 81,
    plot: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's room.",
    comments: ["64e40aacd8c7e9c8d2a7f7b3"],
  },
  {
    title: "Shrek",
    release_date: 989625600000,
    genre: "Animation",
    poster: "/movie-poster/shrek.jpg",
    duration: 90,
    plot: "An ogre sets out to rescue a princess from a tower guarded by a dragon, but discovers that beauty is only skin deep.",
    comments: ["64e40ab7f1c8b2d4e91c7e9d"],
  },
  {
    title: "Finding Nemo",
    release_date: 1054857600000,
    genre: "Animation",
    poster: "/movie-poster/finding-nemo.jpg",
    duration: 100,
    plot: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
    comments: ["64e40ac4187b3a5a91e1c7c3"],
  },
  {
    title: "Spirited Away",
    release_date: 1007424000000,
    genre: "Animation",
    poster: "/movie-poster/spirited-away.jpg",
    duration: 125,
    plot: "A young girl becomes trapped in a mysterious, spirit-filled world and must find a way to free herself and her parents.",
    comments: ["64e40ad1845c1b8d93b2f6d7"],
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    release_date: 1008806400000,
    genre: "Fantasy",
    poster:
      "/movie-poster/the-lord-of-the-rings-the-fellowship-of-the-ring.jpg",
    duration: 178,
    plot: "A young hobbit and his companions set out to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron.",
    comments: ["64e40ae29f7b3c5b7e2c4f19"],
  },
  {
    title: "Harry Potter and the Sorcerer’s Stone",
    release_date: 1005696000000,
    genre: "Fantasy",
    poster: "/movie-poster/harry-potter-and-the-sorcerers-stone.jpg",
    duration: 152,
    plot: "A young boy with a great destiny proves his worth while attending Hogwarts School of Witchcraft and Wizardry.",
    comments: ["64e40af41b7d6c7b95f2b6a5"],
  },
  {
    title: "The Hobbit: An Unexpected Journey",
    release_date: 1355356800000,
    genre: "Fantasy",
    poster: "/movie-poster/the-hobbit-an-unexpected-journey.jpg",
    duration: 169,
    plot: "A reluctant hobbit, Bilbo Baggins, sets out on an unexpected journey to the Lonely Mountain with a spirited group of dwarves.",
    comments: ["64e40b0246e3c29b92c1c8b4"],
  },
  {
    title: "Pan’s Labyrinth",
    release_date: 1167696000000,
    genre: "Fantasy",
    poster: "/movie-poster/pans-labyrinth.jpg",
    duration: 118,
    plot: "In post-Civil War Spain, a young girl encounters a magical labyrinth and its mysterious creatures while trying to escape her brutal stepfather.",
    comments: ["64e40b1325c4d39f73b6f2c9"],
  },
  {
    title: "Se7en",
    release_date: 812236800000,
    genre: "Thriller",
    poster: "/movie-poster/se7en.jpg",
    duration: 127,
    plot: "Two detectives hunt a serial killer who uses the seven deadly sins as motives.",
    comments: ["64e40b226b2d5a6c82d7f3a4"],
  },
  {
    title: "Gone Girl",
    release_date: 1412035200000,
    genre: "Thriller",
    poster: "/movie-poster/gone-girl.jpg",
    duration: 149,
    plot: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    comments: ["64e40b31647c7b9b96f7e4f6"],
  },
  {
    title: "The Silence of the Lambs",
    release_date: 665366400000,
    genre: "Thriller",
    poster: "/movie-poster/the-silence-of-the-lambs.jpg",
    duration: 118,
    plot: "A young FBI cadet must confide in an incarcerated and manipulative killer to receive his help in catching another serial killer.",
    comments: ["64e40b4378c8d69b92e8d1a6"],
  },
  {
    title: "Shutter Island",
    release_date: 1266278400000,
    genre: "Thriller",
    poster: "/movie-poster/shutter-island.jpg",
    duration: 138,
    plot: "A U.S. Marshal investigates the disappearance of a murderess who escaped from a hospital for the criminally insane.",
    comments: ["64e40b5224b3d5d79c1f9e5b"],
  },
  {
    title: "The Social Dilemma",
    release_date: 1601510400000,
    genre: "Documentary",
    poster: "/movie-poster/the-social-dilemma.jpg",
    duration: 94,
    plot: "Explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.",
    comments: ["64e40b62c4a1d5c28a7e1b43"],
  },
  {
    title: "13th",
    release_date: 1475798400000,
    genre: "Documentary",
    poster: "/movie-poster/13th.jpg",
    duration: 100,
    plot: "An in-depth look at the prison system in the United States and how it reveals the nation's history of racial inequality.",
    comments: ["64e40b701f3b7f7a91b8e4d3"],
  },
  {
    title: "Free Solo",
    release_date: 1538006400000,
    genre: "Documentary",
    poster: "/movie-poster/free-solo.jpg",
    duration: 100,
    plot: "Follow Alex Honnold as he attempts to conquer the first free solo climb of famed El Capitan's 900-metre vertical rock face at Yosemite National Park.",
    comments: ["64e40b81a7d5f2b85c3f6c12"],
  },
  {
    title: "Blackfish",
    release_date: 1372118400000,
    genre: "Documentary",
    poster: "/movie-poster/blackfish.jpg",
    duration: 83,
    plot: "A documentary following the controversial captivity of killer whales, and its dangers for both humans and whales.",
    comments: ["64e40b919e5b9f3a94e7b81f"],
  },
];
